spring:
  application:
    name: chatbot
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/chatbotdb
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

configProperties:
  username: ""
  password: ""
  proxy: ""
  port: ""
  workspaceId: ""
  conversationUsername: ""
  conversationPassword: ""
  useProxy: false

url:
  consultarFatura: "http://"
  consultarCliente: "http://"

crm:
  oi-tv: "SINN"

key:
  action: "action"
  cpf: "cpf"
  terminal: "terminal"